---
- name: add influxdb repository
  become: yes
  yum_repository:
    state: present
    description: InfluxDB Repository - CentOS $releasever
    name: influxdb
    baseurl: https://repos.influxdata.com/centos/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: install influxdb
  become: yes
  yum:
    name: influxdb
    state: latest
    update_cache: yes

- name: start influxdb service
  systemd: 
    name: influxdb
    state: started
    enabled: yes
  become: yes
  async: 45
  poll: 5

- name: create database
  become: yes
  influxdb_database:
    hostname: 127.0.0.1
    database_name: telegraf
    state: present

- name: create user with all privileges
  become: yes
  influxdb_user:
    user_name: telegraf
    user_password: telegraf
    grants:
      - database: 'telegraf'
        privilege: 'ALL'
    state: present